config/routes.rb
Rails.application.routes.draw do

  root "welcome#index"

  devise_for :users
  resources :episodes
  
end

app/models/episode.rb
class Episode < ActiveRecord::Base
	def previous
	  Episode.where(["id < ?", id]).last
	end

	def next
	  Episode.where(["id > ?", id]).first
	end

  # Use friendly_id for slugging
  extend FriendlyId
  friendly_id :name, use: :slugged
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  #Use Punit to define user authorization
  def admin?
    role == 'admin'
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Include Punit for user authorization
  include Pundit

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # customize route: redirect to episodes#index after successful sign in
  def after_sign_in_path_for(users)
    episodes_path
  end

  # Redirect user to episodes_path if user is not authorized (Pundit gem)
  rescue_from Pundit::NotAuthorizedError do |exception|
    redirect_to episodes_path, alert: exception.message
  end

end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  before_action :set_episode, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @episodes = Episode.order("created_at ASC").paginate(page: params[:page])
  end

  def show
    authorize @episode
  end

  def new
    @episode = Episode.new
    authorize @episode
  end

  def create
    @episode = Episode.new(episode_params)

    respond_to do |format|
      if @episode.save
        format.html { redirect_to @episode, notice: 'Episode was successfully created.' }
        format.json { render :show, status: :created, location: @episode }
      else
        format.html { render :new }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    authorize @episode
  end

  def update
    authorize @episode
    respond_to do |format|
      if @episode.update(episode_params)
        format.html { redirect_to @episode, notice: 'Episode was successfully updated.' }
        format.json { render :show, status: :ok, location: @episode }
      else
        format.html { render :edit }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @episode.destroy
    respond_to do |format|
      format.html { redirect_to episodes_url, notice: 'Episode was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_episode
      @episode = Episode.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def episode_params
      params.require(:episode).permit(:name, :description, :video_url)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/episodes/_form.html.erb
<%= form_for(@episode) do |f| %>
  <% if @episode.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@episode.errors.count, "error") %> prohibited this episode from being saved:</h2>

      <ul>
      <% @episode.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :video_url %><br>
    <%= f.text_field :video_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/episodes/_header.html.erb
    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          <a class="navbar-brand">壹学</a>

        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <% if user_signed_in? %>
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "Account", edit_user_registration_path %></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          <% else %>
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "Sign Up", new_user_registration_path, class: "pull-right" %></li>
              <li><%= link_to "Login", new_user_session_path, class: "pull-right" %></li>
            </ul>
          <% end %>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

app/views/episodes/edit.html.erb
<h1>Editing episode</h1>

<%= render 'form' %>

<%= link_to 'Show', @episode %> |
<%= link_to 'Back', episodes_path %>

app/views/episodes/index.html.erb
<%= render 'header' %>

<div class="container">

  <% flash.each do |name, msg| %>
    <%= content_tag(:div, msg, class: "alert alert-info") %>
  <% end %>

  <% @episodes.each do |episode| %>

    <div class="panel panel-default">
      <div class="panel-body">
        <h3><%= link_to episode.name, episode %></h3>
        <p><%= episode.description %></p>
      </div>
    </div>

  <% end %>

  <br>
  
  <!-- Hide link to create a new episode if user is NOT authorizied to create -->
  <% if policy(Episode.new).create? %>
    <%= link_to 'New Episode', new_episode_path %>
  <% end %>

  <%= will_paginate @episodes %>
</div>

app/views/episodes/new.html.erb
<h1>New episode</h1>

<%= render 'form' %>

<%= link_to 'Back', episodes_path %>

app/views/episodes/show.html.erb
<!-- required for video.js -->
<link href="//vjs.zencdn.net/4.12/video-js.css" rel="stylesheet">
<script src="//vjs.zencdn.net/4.12/video.js"></script>
<script type="text/javascript">
document.createElement('video');document.createElement('audio');document.createElement('track');
</script>

<!-- Static navbar -->
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <a class="navbar-brand">壹学</a>

    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <% if user_signed_in? %>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "BACK TO COURSE", episodes_path %></li>
        </ul>
      <% end %>
    </div><!--/.nav-collapse -->
  </div>
</nav>
<!-- Static Navbar Ends -->

<!-- video container to host video -->
<div class="container">
  <div class="row">
    <div class="video-container">
    	<video id="video" class="video-js vjs-default-skin vjs-big-play-centered"
    	  controls preload="auto" width="auto" height="auto"
    	  poster="http://video-js.zencoder.com/oceans-clip.png"
    	  data-setup='{"autoplay":false}'>
    	 <source src=<%= @episode.video_url %> type='video/mp4' />
    	</video>
    </div>
  </div>
  
  <!-- panel content starts here -->
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-body">
        <div class="row">
          <!-- text, comments, notes for the episode -->
          <div class="col-md-8 col-xs-12">
            <div class="lesson-notes">
            	<h1><%= @episode.name %></h1>
            	<p><%= @episode.updated_at %></p>
              <p><%= @episode.description %></p>
            </div>
          </div>
          
          <div class="col-md-4 col-xs-12">
          <!-- Navigation Buttons -->
            <nav>
              <ul class="pager">
                <%= link_to("Previous", @episode.previous, class: "btn btn-lg btn-block") if @episode.previous  %>
                <%= link_to("Next", @episode.next, class: "btn btn-lg btn-block") if @episode.next %>
              </ul>
            </nav><!-- Navigation Buttons End -->
          
            <!-- JiaThis Button BEGIN -->
              <div class="share-buttons">
                <div class="jiathis_style_32x32">
                  <a class="jiathis_button_weixin"></a>
                  <a class="jiathis_button_tsina"></a>
                  <a class="jiathis_button_qzone"></a>
                  <a class="jiathis_button_fb"></a>
                  <a class="jiathis_button_googleplus"></a>
                  <a class="jiathis_button_linkedin"></a>
                  <a href="http://www.jiathis.com/share?uid=2009366" class="jiathis jiathis_txt jtico jtico_jiathis" target="_blank"></a>
                  <a class="jiathis_counter_style"></a>
                </div>
                <script type="text/javascript">
                var jiathis_config = {data_track_clickback:'true'};
                </script>
                <script type="text/javascript" src="http://v3.jiathis.com/code/jia.js?uid=2009366" charset="utf-8"></script>
              </div> </ br>
              <!-- JiaThis Button END -->
            </div>
        </div>
        
        <div role="tabpanel">
          <!-- Nav tabs -->
          <ul class="nav nav-tabs" role="tablist">
            <li role="presentation" class="active"><a href="#lesson-notes" aria-controls="home" role="tab" data-toggle="tab">Lesson Notes</a></li>
            <li role="presentation"><a href="#uyan-threads" aria-controls="profile" role="tab" data-toggle="tab">Questions and Comments</a></li>
          </ul>

          <!-- Tab panes -->
          <div class="tab-content">
            <div role="tabpanel" class="tab-pane active" id="lesson-notes">
              <div class="container">
                ABCDE
              </div>
            </div>
            <div role="tabpanel" class="tab-pane" id="uyan-threads">
              <!-- UY BEGIN -->
              <div class="uyan-threads">
                <div id="uyan_frame"></div>
                <script type="text/javascript" src="http://v2.uyan.cc/code/uyan.js?uid=2009366"></script>
              </div>
              <!-- UY END -->
            </div>
          </div><!-- Tab panes end -->

        </div><!-- Tabpanel end -->

      </div>
    </div>
  </div>
  <!-- Panel Content End -->

</div>

app/views/layouts/_header.html.erb
    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          <div class="navbar-brand"><%= link_to "壹学", root_path %></div>

        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "BACK TO COURSE", root_path %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to "Account", edit_user_registration_path %></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "Sign Up", new_user_registration_path %></li>
              <li><%= link_to "Login", new_user_session_path %></li>
            <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="壹学">
  <meta name="author" content="吴硕/Danny Wu">
  <title>壹学－1xuer.com</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
	<%= yield %>
  
</body>
</html>

app/views/welcome/index.html.erb
<!-- Header -->
<a name="about"></a>
<div class="intro-header">
  <div class="container">
    <div class="row">
      <div class="logo pull-left">
        <h3>壹学</h3>
      </div>
      <div class="social">
        <%= link_to new_user_session_path do %>
          <i class="fa fa-sign-in"></i> 登录
        <% end %>
        <%= link_to new_user_registration_path do %>
          <i class="fa fa-user-plus"></i> 注册
        <% end %>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-12">
        <div class="intro-message">
          <h3>一个月的时间，每天只要30分钟，迈出你创业的第一步</h3>
          <hr class="intro-divider">
          <ul class="list-inline">
            <% if user_signed_in? %>
              <%= link_to '继续课程', episodes_path, class: "btn btn-default btn-lg" %>
            <% else %>
              <%= link_to '立即开始', new_user_session_path, class: "btn btn-default btn-lg" %>
            <% end %>
          </ul>
        </div>
      </div>
        <!-- /.container -->
    </div>
  </div>
</div>
<!-- /.intro-header -->

<!-- Page Content -->

<a  name="services"></a>
<div class="content-section-a">

    <div class="container">
        <div class="row">
            <div class="col-lg-5 col-sm-6">
                <hr class="section-heading-spacer">
                <div class="clearfix"></div>
                <h2 class="section-heading">无需任何编程经验，从“0”开始</h2>
                <p class="lead">壹学会陪您一起</p>
            </div>
            <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                <%= image_tag "ipad.png", class: "img-responsive" %>
            </div>
        </div>

    </div>
    <!-- /.container -->

</div>
<!-- /.content-section-a -->

<div class="content-section-b">

    <div class="container">

        <div class="row">
            <div class="col-lg-5 col-lg-offset-1 col-sm-push-6  col-sm-6">
                <hr class="section-heading-spacer">
                <div class="clearfix"></div>
                <h2 class="section-heading">你会学到什么？</h2>
                <p class="lead">在一个月的时间里，我们会陪伴你一起写出你的第一个网站：小众点评。你懂的，就是大众点评的MVP。</p>
            </div>
            <div class="col-lg-5 col-sm-pull-6  col-sm-6">
                <%= image_tag "dog.png", class: "img-responsive" %>
            </div>
        </div>

    </div>
    <!-- /.container -->

</div>
<!-- /.content-section-b -->

<div class="content-section-a">

    <div class="container">

        <div class="row">
            <div class="col-lg-5 col-sm-6">
                <hr class="section-heading-spacer">
                <div class="clearfix"></div>
                <h2 class="section-heading">你会学到什么？</h2>
                <p class="lead">除了编程，我们还会每天和你分享美国的生活</p>
            </div>
            <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                <%= image_tag "phones.png", class: "img-responsive" %>
            </div>
        </div>

    </div>
    <!-- /.container -->

</div>
<!-- /.content-section-a -->

<a  name="contact"></a>
<div class="banner">

    <div class="container">

        <div class="row">
            <div class="col-lg-6">
                <h2>关注我们:</h2>
            </div>
            <div class="col-lg-6">
                <ul class="list-inline banner-social-buttons">
                    <li>
                        <a href="＃" class="btn btn-danger btn-lg"><i class="icon-weibo"></i> <span class="network-name">新郎微博</span></a>
                    </li>
  
                </ul>
            </div>
        </div>

    </div>
    <!-- /.container -->

</div>
<!-- /.banner -->

<!-- Footer -->
<footer>
  <div class="container">
      <div class="row">
          <div class="col-lg-12">
              <ul class="list-inline">
                  <li>
                      <a href="#">主页</a>
                  </li>
                  <li class="footer-menu-divider">&sdot;</li>
                  <li>
                      <a href="#about">我们的团队</a>
                  </li>
                  <li class="footer-menu-divider">&sdot;</li>
                  <li>
                      <a href="#contact">联系我们</a>
                  </li>
              </ul>
              <p class="copyright text-muted small">Copyright &copy; 壹学儿 2015. All Rights Reserved</p>
          </div>
      </div>
  </div>
</footer>